#!/usr/bin/env python3

import configparser
import os

Config = configparser.ConfigParser()
homeDir = os.environ.get('HOME') + '/'
confName = homeDir + '/.wallpyper.conf'

# Checks if conf file exists.
if os.path.isfile(confName):
    conf = open(confName, 'r')
else:
    conf = open(confName, 'w+')
    conf.write('[Configuration]\n' +
               'Directory: ' + homeDir + 'Pictures\n'
               'Pictures: *')
    conf.close()
    conf = open(confName, 'r')

Config.read(confName)


def ConfigSectionMap(section):
    dict1 = {}
    options = Config.options(section)
    for option in options:
        try:
            dict1[option] = Config.get(section, option)
            if dict1[option] == -1:
                DebugPrint("skip: %s" % option)
        except:
            print("exception on %s!" % option)
            dict1[option] = None
    return dict1

root = ConfigSectionMap("Configuration")["directory"]
path = os.path.join(root, "targetdirectory")
fileList = []

for path, subdirs, files in os.walk(root):
    for name in files:
        fileList.append(os.path.join(path, name))

print(fileList[1])
conf.close()
